/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CurationRouteImport } from './routes/curation'
import { Route as EmbeddingsRouteImport } from './routes/embeddings'
import { Route as EvalRouteImport } from './routes/eval'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HealthRouteImport } from './routes/health'
import { Route as RecallRouteImport } from './routes/recall'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions_.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddingsRoute = EmbeddingsRouteImport.update({
  id: '/embeddings',
  path: '/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRoute = EvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallRoute = RecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions_/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/curation': typeof CurationRoute
  '/embeddings': typeof EmbeddingsRoute
  '/eval': typeof EvalRoute
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/recall': typeof RecallRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/curation': typeof CurationRoute
  '/embeddings': typeof EmbeddingsRoute
  '/eval': typeof EvalRoute
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/recall': typeof RecallRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/curation': typeof CurationRoute
  '/embeddings': typeof EmbeddingsRoute
  '/eval': typeof EvalRoute
  '/graph': typeof GraphRoute
  '/health': typeof HealthRoute
  '/recall': typeof RecallRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/sessions_/$sessionId': typeof SessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/curation'
    | '/embeddings'
    | '/eval'
    | '/graph'
    | '/health'
    | '/recall'
    | '/sessions'
    | '/settings'
    | '/timeline'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/curation'
    | '/embeddings'
    | '/eval'
    | '/graph'
    | '/health'
    | '/recall'
    | '/sessions'
    | '/settings'
    | '/timeline'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/curation'
    | '/embeddings'
    | '/eval'
    | '/graph'
    | '/health'
    | '/recall'
    | '/sessions'
    | '/settings'
    | '/timeline'
    | '/sessions_/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  CurationRoute: typeof CurationRoute
  EmbeddingsRoute: typeof EmbeddingsRoute
  EvalRoute: typeof EvalRoute
  GraphRoute: typeof GraphRoute
  HealthRoute: typeof HealthRoute
  RecallRoute: typeof RecallRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curation': {
      id: '/curation'
      path: '/curation'
      fullPath: '/curation'
      preLoaderRoute: typeof CurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embeddings': {
      id: '/embeddings'
      path: '/embeddings'
      fullPath: '/embeddings'
      preLoaderRoute: typeof EmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval': {
      id: '/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof EvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recall': {
      id: '/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof RecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/$sessionId': {
      id: '/sessions_/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  CurationRoute: CurationRoute,
  EmbeddingsRoute: EmbeddingsRoute,
  EvalRoute: EvalRoute,
  GraphRoute: GraphRoute,
  HealthRoute: HealthRoute,
  RecallRoute: RecallRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
